on:
  schedule:
    - cron: '9 0 * * *'
  push:
    branches:
      - 'master'

jobs:
  update-apod:
    runs-on: ubuntu-latest
    steps:
      - name: Get latest APOD
        id: apod
        uses: fjogeleit/http-request-action@v1.11.0
        with:
          url: 'https://api.nasa.gov/planetary/apod?api_key=DEMO_KEY'
          method: 'GET'

      - name: Update index.html
        uses: actions/checkout@v3
        uses: actions/setup-node@v3
        with:
          node_version: '14'
        run: npm install jsdom
        run: node update-apod.js ${{ steps.apod.outputs.response }}
        uses: test-room-7/action-update-file@v1.6.0
        with:
          file-path: index.html
          commit-msg: Update index.html
          github-token: ${{ secrets.GITHUB_TOKEN }}
